### PR TITLE
Remotes field in description, slight namespace tweak

### PR DESCRIPTION
**Pull request by alanocallaghan**
`Remotes:` means devtools will fetch R2GUESS, since it's also not on CRAN/Bioc.

The namespace change should fix `replacing previous import ‘data.table::melt’ by ‘reshape::melt’ when loading ‘GUESSFM’`

### CODE REVIEW

**Comment by alanocallaghan** [comment]
Ah, I lied. There's still an `@import data.table` so the warning stays

**Comment by chr1swallace** [comment]
what's the warning?

**Comment by alanocallaghan** [comment]
```
Warning message:
replacing previous import ‘data.table::melt’ by ‘reshape::melt’ when loading ‘GUESSFM’ 
```

The issue is `melt` gets imported when datatable's namespace is imported, then gets clobbered by the reshape2 version

**Comment by chr1swallace** [comment]
Is the warning when loading or installing?

**Comment by alanocallaghan** [comment]
Both, though I think the install ones are just when it's loaded during install

**Comment by chr1swallace** [comment]
I think the solution will be to import only melt.matrix and melt.list
from reshape, and then call them directly where needed.

Is this warning causing you trouble?

**Comment by alanocallaghan** [comment]
Could also not import them and just call reshape2::melt where they're needed.

No, just mild inconvenience from log files filling up

**Pull request closed without merging**
